spring:
  application:
    name: "spring_datajpa"
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: system
    password: ashok
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        enabled: true